<a href="https://colab.research.google.com/github/Rakeshnaidu03/Rakesh-Chanda/blob/main/(Rakesh)ML_ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Part A#


import numpy as np

# Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print array shape
print("Shape of the array after reshaping:", reshaped_array.shape)

# Replace the max in each row by 0
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

print("Array after replacing max in each row with 0:\n", reshaped_array)

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print shape, type, and data type of the array
print("Shape of the 2D array:", array_4x3.shape)
print("Type of the array:", type(array_4x3))
print("Data type of the array:", array_4x3.dtype)


Shape of the array after reshaping: (3, 5)
Array after replacing max in each row with 0:
 [[ 0  9  9  7 18]
 [10 14  0  9  5]
 [ 8 14  8  0  6]]
Shape of the 2D array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [8]:
import numpy as np

# Given square array
A = np.array([[3, -2], [1, 0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [9]:
import numpy as np

# Define the given array
given_array = np.array([[0, 1, 2],
                        [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(given_array)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)



Sum of the diagonal elements: 4


In [10]:
import numpy as np

# Define the original array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

# Reshape to 2x3
reshaped_array_2x3 = np.reshape(original_array, (2, 3))

# Reshape to 3x2
reshaped_array_3x2 = np.reshape(original_array, (3, 2))

# Print the reshaped arrays
print("Original Array:")
print(original_array)
print("\nReshaped to 2x3:")
print(reshaped_array_2x3)
print("\nReshaped to 3x2:")
print(reshaped_array_3x2)


Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]

Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]


**Part B**

In [13]:
import pandas as pd

# 1. Read the provided CSV file 'data.csv'
df = pd.read_csv('data (1).csv')

# 2. Show the basic statistical description about the data
basic_stats = df.describe()
print("Basic Statistical Description:")
print(basic_stats)

# 3. Check if the data has null values and replace them with the mean
if df.isnull().values.any():
    print("\nThe data has null values.")
    # Replace null values with mean
    df.fillna(df.mean(), inplace=True)
    print("Null values replaced with mean.")

# 4. Select at least two columns and aggregate the data using: min, max, count, mean
aggregated_data = df[['Calories', 'Pulse']].agg(['min', 'max', 'count', 'mean'])
print("\nAggregated Data (Calories and Pulse):")
print(aggregated_data)

# 5. Filter the dataframe to select the rows with calories values between 500 and 1000
filtered_calories = df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]
print("\nRows with Calories between 500 and 1000:")
print(filtered_calories)

# 6. Filter the dataframe to select the rows with calories values > 500 and pulse < 100
filtered_calories_pulse = df[(df['Calories'] > 500) & (df['Pulse'] < 100)]
print("\nRows with Calories > 500 and Pulse < 100:")
print(filtered_calories_pulse)

# 7. Create a new “df_modified” dataframe that contains all the columns from df except for “Maxpulse”
df_modified = df.drop(columns=['Maxpulse'])

# 8. Delete the “Maxpulse” column from the main df dataframe
df.drop(columns=['Maxpulse'], inplace=True)

# 9. Convert the datatype of Calories column to int datatype
df['Calories'] = df['Calories'].astype(int)

# Display modified dataframe
print("\nModified DataFrame (df_modified):")
print(df_modified.head())
print("\nOriginal DataFrame (df) after deletion of 'Maxpulse' column and conversion of 'Calories' column to int:")
print(df.head())


Basic Statistical Description:
         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

The data has null values.
Null values replaced with mean.

Aggregated Data (Calories and Pulse):
          Calories       Pulse
min      50.300000   80.000000
max    1860.400000  159.000000
count   169.000000  169.000000
mean    375.790244  107.461538

Rows with Calories between 500 and 1000:
     Duration  Pulse  Maxpulse  Calories
51         80    123       146     643.1
62        160    109       135     853.0
65        180     90       130     800.4
66        150  