<a href="https://colab.research.google.com/github/Rakeshnaidu03/Rakesh-Chanda/blob/main/RakeshChanda_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print the array shape
print("Array Shape:")
print(reshaped_array.shape)

# Replace the max in each row by 0
for row in reshaped_array:
    max_value = np.max(row)
    row[row == max_value] = 0

# Print the modified array
print("\nModified Array:")
print(reshaped_array)



Array Shape:
(3, 5)

Modified Array:
[[14 12  0  2 14]
 [ 8  7  4  0  1]
 [10  8 12  0 12]]


In [10]:
import numpy as np

# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array_2d = np.zeros((4, 3), dtype=np.int32)

# Print the shape of the array
print("Array Shape:", array_2d.shape)

# Print the type of the array
print("Array Type:", type(array_2d))

# Print the data type of the array elements
print("Data Type of Array Elements:", array_2d.dtype)


Array Shape: (4, 3)
Array Type: <class 'numpy.ndarray'>
Data Type of Array Elements: int32


In [12]:
import numpy as np

# Create the given array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Calculate the sum of the diagonal elements
diagonal_sum = np.trace(array)

# Print the sum of the diagonal elements
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [13]:
import numpy as np

# Create an array of odd numbers between 10 and 70
odd_array = np.arange(11, 71, 2)

# Create an array of even numbers between 10 and 70
even_array = np.arange(10, 71, 2)

# Print both arrays
print("Odd Numbers Array:", odd_array)
print("Even Numbers Array:", even_array)


Odd Numbers Array: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Even Numbers Array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]


In [15]:
import numpy as np

# Create two arrays of the same size
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Example operations:
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Print the results
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)


Addition Result: [ 6  8 10 12]
Subtraction Result: [-4 -4 -4 -4]
Multiplication Result: [ 5 12 21 32]


In [16]:
import numpy as np

# Create the given array
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sort by row (axis=1) in ascending order
sorted_by_row = np.sort(array, axis=1)

# Sort by column (axis=0) in ascending order
sorted_by_column = np.sort(array, axis=0)

# Print the sorted arrays
print("Sorted by Row (Ascending):")
print(sorted_by_row)

print("\nSorted by Column (Ascending):")
print(sorted_by_column)


Sorted by Row (Ascending):
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sorted by Column (Ascending):
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [19]:
import numpy as np

# Create the array with NaN values
array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

# Find missing data by returning a Boolean array (True for NaN values, False otherwise)
missing_data_mask = np.isnan(array)

# Print the Boolean array
print("Missing Data (True/False):")
print(missing_data_mask)



Missing Data (True/False):
[[False False  True False]
 [False False False False]
 [False  True False  True]]
